export const COLUMN = {
  PRODUCT_NAME: "D",
  VARIATION: "E",
  PRICE: "F",
  WRONG_DEFECTIVE_RETURN_DISCOUNT: "G",
  MRP: "H",
  GST: "I",
  HSN: "J",
  WEIGHT: "K",
  INVENTORY: "L",
  COUNTRY: "M",

  MANUFACTURER: "N",
  MANUFACTURER_ADDRESS: "O",
  MANUFACTURER_PINCODE: "P",

  PACKER: "Q",
  PACKER_ADDRESS: "R",
  PACKER_PINCODE: "S",

  IMPORTER: "T",
  IMPORTER_ADDRESS: "U",
  IMPORTER_PINCODE: "V",

  COLOR: "W",
  MODEL: "X",
  GENERIC_NAME: "Y",
  MATERIAL: "Z",

  QUANTITY: "AA",
  LENGTH: "AB",
  WIDTH: "AC",

  THEME: "AD",
  TYPE: "AE",

  IMAGE1: "AF",
  IMAGE2: "AG",
  IMAGE3: "AH",
  IMAGE4: "AI",

  STYLE_ID: "AJ",
  SKU: "AK",

  BRAND_NAME: "AL",
  GROUP_ID: "AM",

  DESCRIPTION: "AN",
  BRAND: "AO",
} as const;
